### ISSUE TITLE
Convert the script into a Ritchie CLI formula

### ISSUE THREAD

**Issue by GuillaumeFalourd** [sumitmaji/kubernetes#1]
Hi @sumitmaji , what a great repository, well done ! 🥇 

I would like to discuss about [Ritchie CLI](https://docs.ritchiecli.io/) and how your script could executed another way, based on your current implementation.

It's an open source product our team has created and that allows to transform scripts into formulas (in our context, formulas are automations that can be executed through command line, locally or with Docker, with necessary dependencies).

Your script is very powerful and we would love to have it as a formula to show the community a use case of our product with clusters and kubernetes.

Would you like to take a look at our documentation (link above) and give us a feedback about the tool ?

You could create your own formulas repository to share it, or add it to our [commons formulas repository](https://github.com/ZupIT/ritchie-formulas). 

If you wish, we can also do it together to take the opportunity to discuss about the product.

Regards,

**Comment by sumitmaji** [comment]
Will look into it later
